--DDL
CREATE TABLE ZZZUSER(
ID VARCHAR2(30) PRIMARY KEY,
PASSWORD VARCHAR2(50) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
PHONE VARCHAR2(50) NOT NULL,
JOINDATE DATE DEFAULT CURRENT_DATE,
DELFLAG VARCHAR(1) NOT NULL,
AUTH VARCHAR(1) NOT NULL
)

--DML
--회원가입
INSERT INTO ZZZUSER
			(ID, PASSWORD, NAME, 
			EMAIL, PHONE, JOINDATE, 
			DELFLAG, AUTH)
		VALUES('sky123', '123123', '하늘', 
			'sky123@naver.com', '01012345678', CURRENT_DATE, 
			'Y', 'U');
		
INSERT INTO ZZZUSER
			(ID, PASSWORD, NAME, 
			EMAIL, PHONE, JOINDATE, 
			DELFLAG, AUTH)
		VALUES('red789', '123123', '빨강', 
			'red23@naver.com', '01044445678', CURRENT_DATE, 
			'Y', 'U');		

INSERT INTO ZZZUSER
			(ID, PASSWORD, NAME, 
			EMAIL, PHONE, JOINDATE, 
			DELFLAG, AUTH)
		VALUES('green', 'green', '초록색', 
			'green@daum.net', '01098789753', CURRENT_DATE, 
			'Y', 'U');
		
INSERT INTO ZZZUSER
			(ID, PASSWORD, NAME, 
			EMAIL, PHONE, JOINDATE, 
			DELFLAG, AUTH)
		VALUES('admin', 'admin', '관리자', 
			'admin@naver.com', '01011111111', CURRENT_DATE, 
			'Y', 'A');
		
		
--로그인
SELECT ID, NAME ,EMAIL ,PHONE ,JOINDATE , AUTH 
	FROM ZZZUSER z 
	WHERE ID = 'green'
	AND PASSWORD  = 'green'
	AND DELFLAG = 'Y';


--ID중복검사
SELECT COUNT(*) 
	FROM ZZZUSER z 
	WHERE ID = 'green'; 


--정보수정
UPDATE ZZZUSER SET PASSWORD = '123456', 
					EMAIL = 'aaaa123@gmail.com', 
					PHONE = '01088884444'
			WHERE ID = 'green';
		

		
		
